name: video_optimiaztion
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  cached_network_image: ^3.2.0
  cached_video_player: ^2.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
 
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  video_player: ^2.4.5
  visibility_detector: ^0.2.2

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
